//
//  StyleKit.h
//  DetourFX
//
//  Created by Aurelius Prochazka on 4/16/15.
//  Copyright (c) 2015 AudioKit. All rights reserved.
//
//  Generated by PaintCode (www.paintcodeapp.com)
//

#import <Foundation/Foundation.h>
#import <UIKit/UIKit.h>


@interface StyleKit : NSObject

// Drawing Methods
+ (void)drawHeadAndSpeakerWithAzimuth: (CGFloat)azimuth;

@end
